
package br.com.oobj.cxf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.2
 * Wed Nov 05 11:12:59 BRST 2014
 * Generated source version: 3.0.2
 */

@XmlRootElement(name = "imprimirNotaDaEmpresa", namespace = "http://cxf.oobj.com.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "imprimirNotaDaEmpresa", namespace = "http://cxf.oobj.com.br/")

public class ImprimirNotaDaEmpresa {

    @XmlElement(name = "empresa", namespace="http://cxf.oobj.com.br/")
    private java.lang.String empresa;

    public java.lang.String getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(java.lang.String newEmpresa)  {
        this.empresa = newEmpresa;
    }

}

