
package br.com.oobj.cxf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.2
 * Wed Nov 05 11:12:59 BRST 2014
 * Generated source version: 3.0.2
 */

@XmlRootElement(name = "imprimirNotaDaEmpresaResponse", namespace = "http://cxf.oobj.com.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "imprimirNotaDaEmpresaResponse", namespace = "http://cxf.oobj.com.br/")

public class ImprimirNotaDaEmpresaResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

