package br.com.oobj.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-11-05T11:59:43.159-02:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://cxf.oobj.com.br/", name = "NotaFiscalServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface NotaFiscalServicePortType {

    @WebResult(name = "return", targetNamespace = "http://cxf.oobj.com.br/")
    @RequestWrapper(localName = "imprimirNotaDaEmpresa", targetNamespace = "http://cxf.oobj.com.br/", className = "br.com.oobj.cxf.ImprimirNotaDaEmpresa")
    @WebMethod
    @ResponseWrapper(localName = "imprimirNotaDaEmpresaResponse", targetNamespace = "http://cxf.oobj.com.br/", className = "br.com.oobj.cxf.ImprimirNotaDaEmpresaResponse")
    public java.lang.String imprimirNotaDaEmpresa(
        @WebParam(name = "empresa", targetNamespace = "http://cxf.oobj.com.br/")
        java.lang.String empresa
    );

    @WebResult(name = "return", targetNamespace = "http://cxf.oobj.com.br/")
    @RequestWrapper(localName = "consomeXML", targetNamespace = "http://cxf.oobj.com.br/", className = "br.com.oobj.cxf.ConsomeXML")
    @WebMethod
    @ResponseWrapper(localName = "consomeXMLResponse", targetNamespace = "http://cxf.oobj.com.br/", className = "br.com.oobj.cxf.ConsomeXMLResponse")
    public java.lang.String consomeXML(
        @WebParam(name = "nfeEmXML", targetNamespace = "http://cxf.oobj.com.br/")
        java.lang.String nfeEmXML
    );
}
