
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package br.com.oobj.cxf;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-11-05T11:59:43.144-02:00
 * Generated source version: 3.0.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "NotaFiscalService",
                      portName = "NotaFiscalServicePort",
                      targetNamespace = "http://cxf.oobj.com.br/",
                      wsdlLocation = "file:/D:/workspace geral/ws-cxf-client/src/main/webapp/wsdl/notafiscalservice.wsdl",
                      endpointInterface = "br.com.oobj.cxf.NotaFiscalServicePortType")
                      
public class NotaFiscalServicePortImpl implements NotaFiscalServicePortType {

    private static final Logger LOG = Logger.getLogger(NotaFiscalServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see br.com.oobj.cxf.NotaFiscalServicePortType#imprimirNotaDaEmpresa(java.lang.String  empresa )*
     */
    public java.lang.String imprimirNotaDaEmpresa(java.lang.String empresa) {
        LOG.info("Executing operation imprimirNotaDaEmpresa");
        System.out.println(empresa);
        try {
            java.lang.String _return = "_return1693842963";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.com.oobj.cxf.NotaFiscalServicePortType#consomeXML(java.lang.String  nfeEmXML )*
     */
    public java.lang.String consomeXML(java.lang.String nfeEmXML) { 
        LOG.info("Executing operation consomeXML");
        System.out.println(nfeEmXML);
        try {
        	java.lang.String _return = "whatafuck";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
