package br.com.oobj.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-11-05T11:59:43.167-02:00
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "NotaFiscalService", 
                  wsdlLocation = "file:/D:/workspace geral/ws-cxf-client/src/main/webapp/wsdl/notafiscalservice.wsdl",
                  targetNamespace = "http://cxf.oobj.com.br/") 
public class NotaFiscalService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cxf.oobj.com.br/", "NotaFiscalService");
    public final static QName NotaFiscalServicePort = new QName("http://cxf.oobj.com.br/", "NotaFiscalServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/workspace geral/ws-cxf-client/src/main/webapp/wsdl/notafiscalservice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NotaFiscalService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/workspace geral/ws-cxf-client/src/main/webapp/wsdl/notafiscalservice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NotaFiscalService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NotaFiscalService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotaFiscalService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NotaFiscalService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NotaFiscalService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NotaFiscalService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns NotaFiscalServicePortType
     */
    @WebEndpoint(name = "NotaFiscalServicePort")
    public NotaFiscalServicePortType getNotaFiscalServicePort() {
        return super.getPort(NotaFiscalServicePort, NotaFiscalServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotaFiscalServicePortType
     */
    @WebEndpoint(name = "NotaFiscalServicePort")
    public NotaFiscalServicePortType getNotaFiscalServicePort(WebServiceFeature... features) {
        return super.getPort(NotaFiscalServicePort, NotaFiscalServicePortType.class, features);
    }

}
